kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: hyperledger
  name: explorer
  labels:
    app: explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer
  template:
    metadata:
      labels:
        app: explorer
    spec:
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: pvc1
      containers:
        - name: explorer
          image: hyperledger/explorer:1.1.3
          env:
            - name: DATABASE_HOST
              value: "explorer-db"
            - name: DATABASE_DATABASE
              value: "database1"
            - name: DATABASE_USERNAME
              value: "user1"
            - name: DATABASE_PASSWORD
              value: "user1pw"
            - name: LOG_LEVEL_APP
              value: "debug"
            - name: LOG_LEVEL_DB
              value: "debug"
            - name: LOG_LEVEL_CONSOLE
              value: "info"
            - name: LOG_CONSOLE_STDOUT
              value: "true"
            - name: DISCOVERY_AS_LOCALHOST
              value: "false"
          volumeMounts:
            - mountPath: /opt/explorer/app/platform/fabric/config.json
              name: vol1
              subPath: explorer/config.json
            - mountPath: /opt/explorer/app/platform/fabric/connection-profile
              name: vol1
              subPath: explorer/connection-profile
            - mountPath: /tmp/crypto
              name: vol1
              subPath: organizations
            - mountPath: /opt/explorer/wallet
              name: vol1
              subPath: explorer/walletstore
---
apiVersion: v1
kind: Service
metadata:
  namespace: hyperledger
  name: explorer
spec:
  type: ClusterIP
  selector:
    app: explorer
  ports:
    - port: 8080
      targetPort: 8080
