kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: hyperledger
  name: explorer-db
  labels:
    app: explorer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer-db
  template:
    metadata:
      labels:
        app: explorer-db
    spec:
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: pvc1
      containers:
        - name: explorer-db
          image: hyperledger/explorer-db:1.1.3
          env:
            - name: DATABASE_DATABASE
              value: "database1"
            - name: DATABASE_USERNAME
              value: "user1"
            - name: DATABASE_PASSWORD
              value: "user1pw"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: vol1
              subPath: pgdata/
---
apiVersion: v1
kind: Service
metadata:
  namespace: hyperledger
  name: explorer-db
spec:
  type: ClusterIP
  selector:
    app: explorer-db
  ports:
    - port: 5432
      targetPort: 5432
