apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hyperledger
  name: orderer2
  labels:
    app: orderer2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderer2
  template:
    metadata:
      labels:
        app: orderer2
    spec:
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: pvc1
      containers:
        - name: orderer2
          image: hyperledger/fabric-orderer:2.2.1
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric
          env:
            - name: FABRIC_LOGGING_SPEC
              value: "INFO"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_BOOTSTRAPMETHOD
              value: "file"
            - name: ORDERER_GENERAL_BOOTSTRAPFILE
              value: "/vol1/genesis.block"
            - name: ORDERER_GENERAL_LOCALMSPID
              value: "OrderersMSP"
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: "/var/hyperledger/orderer/msp"
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: "/var/hyperledger/orderer/tls/server.key"
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: "/var/hyperledger/orderer/tls/signcerts/cert.pem"
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/var/hyperledger/orderer/tls/tlscacerts/tls-localhost-7054.pem]"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: "/var/hyperledger/orderer/tls/server.key"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: "/var/hyperledger/orderer/tls/signcerts/cert.pem"
            - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
              value: "[/var/hyperledger/orderer/tls/tlscacerts/tls-localhost-7054.pem]"
          volumeMounts:
            - mountPath: /vol1
              name: vol1
            - mountPath: /var/hyperledger/orderer/
              name: vol1
              subPath: organizations/ordererOrganizations/orderers/orderers/orderer2/
            - mountPath: /var/hyperledger/production/orderer/
              name: vol1
              subPath: orderers/orderer2/
---
apiVersion: v1
kind: Service
metadata:
  namespace: hyperledger
  name: orderer2
spec:
  type: ClusterIP
  selector:
    app: orderer2
  ports:
    - port: 7050
      targetPort: 7050
