kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: hyperledger
  name: org2-ca
  labels:
    app: org2-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org2-ca
  template:
    metadata:
      labels:
        app: org2-ca
    spec:
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: pvc1
      containers:
        - name: org2-ca
          image: hyperledger/fabric-ca:1.4.7
          env:
            - name: FABRIC_CA_SERVER_HOME
              value: "/etc/hyperledger/fabric-ca-server"
            - name: FABRIC_CA_SERVER_CA_NAME
              value: "org2-ca"
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_CLIENT_HOME
              value: "/etc/hyperledger/fabric-ca-client"
            - name: FABRIC_CA_CLIENT_TLS_CERTFILES
              value: "/etc/hyperledger/fabric-ca-server/tls-cert.pem"
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server
              name: vol1
              subPath: organizations/fabric-ca/org2
            - mountPath: /etc/hyperledger/fabric-ca-client
              name: vol1
              subPath: organizations/peerOrganizations/org2
---
apiVersion: v1
kind: Service
metadata:
  namespace: hyperledger
  name: org2-ca
spec:
  type: ClusterIP
  selector:
    app: org2-ca
  ports:
    - port: 7054
      targetPort: 7054
