Organizations:
  - &Orderers
    Name: Orderers
    ID: OrderersMSP
    MSPDir: ../organizations/ordererOrganizations/orderers/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrderersMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrderersMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrderersMSP.admin')"
  - &Org1
    Name: Org1
    ID: Org1MSP
    MSPDir: ../organizations/peerOrganizations/org1/msp
    AnchorPeers:
      - Host: org1-peer0
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
  - &Org2
    Name: Org2
    ID: Org2MSP
    MSPDir: ../organizations/peerOrganizations/org2/msp
    AnchorPeers:
      - Host: org2-peer0
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org2MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
Capabilities:
  Global: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true
Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities
Orderer: &OrdererDefaults
  OrdererType: etcdraft
  EtcdRaft:
    Consenters:
      - Host: orderer0
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/orderers/orderers/orderer0/tls/signcerts/cert.pem
        ServerTLSCert: ../organizations/ordererOrganizations/orderers/orderers/orderer0/tls/signcerts/cert.pem
      - Host: orderer1
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/orderers/orderers/orderer1/tls/signcerts/cert.pem
        ServerTLSCert: ../organizations/ordererOrganizations/orderers/orderers/orderer1/tls/signcerts/cert.pem
      - Host: orderer2
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/orderers/orderers/orderer2/tls/signcerts/cert.pem
        ServerTLSCert: ../organizations/ordererOrganizations/orderers/orderers/orderer2/tls/signcerts/cert.pem
  Addresses:
    - orderer0:7050
    - orderer1:7050
    - orderer2:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
    - *Orderers
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities
Profiles:
  OrdererGenesis:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *Orderers
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      MyConsortium:
        Organizations:
          - *Org1
          - *Org2
  MyChannel:
    Consortium: MyConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
        - *Org2
      Capabilities:
        <<: *ApplicationCapabilities
